# netlify.toml

[build]
  command = "npm install && npm run build"  # Specify your build command here
  # publish = "dist"  # Specify the directory to publish

# Forcefully install dependencies before the build process
[build.environment]
  FORCE_INSTALL = "true"
